Algoritmo "semnome"
// Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
//ÍMPAR.
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("insira um número: ")
leia(numero)
se (numero mod 2 = 0) entao
    escreva("O numero",numero," é par")
senao
     escreva("o numero",numero," é impar")
fimse
Fimalgoritmo