Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2025
Var
a,b,c, delta:real

Inicio
escreva("Para encontrar o delta, insira o valor de a: ")
leia(a)
escreva("Insira o valor de b: ")
leia(b)
escreva("Insira o valor de c: ")
leia(c)
delta <- b^2 - 4*a*c
escreva("o delta é igual a:", delta)
Fimalgoritmo